### ISSUE TITLE
[REFACTOR] like 의 service 내 HttpServlet인자를 받는 것 제거 및 controller에서 ResponseEntity 반환하도록 수정

### ISSUE THREAD

**Issue by seokhwan-an** [seokhwan-an/autumn_festival_back_improvement#17]
## 📚개선할 기능 
- like service 내 인자로 httpServletRequst를 받는 것이 있는데 이를 필요한 정보만 받도록 수정
- controller의 응답값을 http 규격에 맞고 http status code를 다룰 수 있는 ResponseEntity로 감싸서 반환하고자 합니다.

## ✏️Todo
- [x] boothController에 있는 like end point 옮기기
- [x] likeService 파라미터 수정
- [x] likeController ResponseEntity를 응답하도록 수정
