### ISSUE TITLE
[REFACTOR] 부스 댓글과 관련된 전반적인 문제를 해결한다.

### ISSUE THREAD

**Issue by seokhwan-an** [seokhwan-an/autumn_festival_back_improvement#23]
## 📚개선할 기능 
부스 댓글과 관련된 코드의 전반적인 문제를 해결한다.

## ✏️Todo
- [ ] 댓글 엔티티 불필요한 어노테이션 제거
- [ ] 댓글 service에서 httpServletRequest 인자로 받는 것 제거
- [ ] controller에서 ResponseEntity 반환하도록 수정
