### ISSUE TITLE
[REFACTOR] menu와 관련된 전반적인 문제를 해결하고자 한다.

### ISSUE THREAD

**Issue by seokhwan-an** [seokhwan-an/autumn_festival_back_improvement#29]
## 📚개선할 기능 
menu와 관련된 코드의 전반적인 문제를 해결한다.

## ✏️Todo
- [x] menu 엔티티에 불필요한 어노테이션 제거
- [x] menu service 내 dto -> entity 변환, entity -> dto 변환 로직 제거
- [x] booth controller 내 menu end point는 menu controller로 분리
- [x] menu controller 응답 수정
