### ISSUE TITLE
[FEAT] menu 테스트 코드 추가

### ISSUE THREAD

**Issue by seokhwan-an** [seokhwan-an/autumn_festival_back_improvement#31]
## 💡구현 기능
menu와 관련된 기능에 테스트 코드를 추가한다.

## ✏️Todo
- [x] menu entity 테스트 추가
- [x] menu service 테스트 추가
- [x] menu controller 테스트 추가
