### ISSUE TITLE
[REFACTOR] notification과 관련된 전반적인 문제를 해결한다.

### ISSUE THREAD

**Issue by seokhwan-an** [seokhwan-an/autumn_festival_back_improvement#33]
## 📚개선할 기능 
공지사항과 관련해서 전반적인 문제를 해결하고자 한다. 

## ✏️Todo
- [x] notification 엔티티 내 불필요한 어노테이션 제거
- [x] 구현체 대신에 추상체 반환하기
- [x] notification service 내 dto 생성책임 제거하기
- [x] notification controller의 반환값 responseEntity로 감싸기
