### ISSUE TITLE
[FEAT] notification 테스트 코드 추가

### ISSUE THREAD

**Issue by seokhwan-an** [seokhwan-an/autumn_festival_back_improvement#35]
## 💡구현 기능
notification 테스트 코드 추가한다.

## ✏️Todo
- [x] notification entity 단위 테스트 추가
- [x] notification service 테스트 추가
- [x] notification controller 테스트 추가
