### ISSUE TITLE
[REFACTOR] 테스트 템플릿 만들기

### ISSUE THREAD

**Issue by seokhwan-an** [seokhwan-an/autumn_festival_back_improvement#40]
## 📚개선할 기능 
- 현재 모든 테스트 파일에 공통으로 들어가는 부분이 있습니다.
    - service : 테스트간 격리성 보장을 위한 데이터 제거 코드
    - controller : port 설정, 테스트간 격리성 보장을 위한 데이터 제거 코드
- 공통으로 이용되는 부분을 템플릿화하여 불필요한 설정을 제거해 나가고자 합니다

## ✏️Todo
- [ ] entityManager를 통해 테이블 내 데이터를 제거하는 component 추가
- [ ] 통합테스트 템플릿 추가
- [ ] 인수테스트 템플릿 추가
