### ISSUE TITLE
[REFACTOR] Booth 코드 내 불필요한 어노테이션 및 책임 수정

### ISSUE THREAD

**Issue by seokhwan-an** [seokhwan-an/autumn_festival_back_improvement#6]
## 📚개선할 기능 
현재 booth 코드에는 문제점이 많습니다. 실제로 동작하지 않은 어노테이션들을 포함하고 있고 service에서 `HttpServletRequest`를 직접 접근하고 있습니다. 불필요한 어노테이션을 제거하고 service에서는 dto를 인자로 받는 방식으로 수정해나가려고 합니다.

## ✏️Todo
- [ ] 불필요한 `@Notnull` 제거
- [ ] 불필요한 `@JsonManagedReference` 제거
- [ ] service 단에서 HttpServelRequest를 받는 것이 아닌 dto를 넘겨 받도록 수정
